# Generated by Django 4.2.7 on 2026-08-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_item_cost_price_hc_item_min_selling_price_hc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost_price_hc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_selling_price_hc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='selling_price_hc',
        ),
    ]
