# Generated by Django 4.2.7 on 2026-08-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_saleinvoice_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerledger',
            name='hc_amount',
        ),
        migrations.RemoveField(
            model_name='customerledger',
            name='hc_currency',
        ),
        migrations.RemoveField(
            model_name='customerledger',
            name='hc_exchange_rate',
        ),
        migrations.RemoveField(
            model_name='customerledger',
            name='hc_running_balance',
        ),
    ]
