# Generated by Django 4.2.7 on 2026-08-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_socialmediapost_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='exchange_rate_updated_at',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='hard_currency',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='hard_currency_mode',
        ),
        migrations.DeleteModel(
            name='ExchangeRateHistory',
        ),
    ]
