# Generated by Django 4.2.7 on 2026-08-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='currency',
        ),
    ]
