# Generated by Django 4.2.7 on 2026-08-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0006_treasury_transfer_movement_cascade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasury',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='treasury',
            name='is_hard_currency',
        ),
    ]
